// src/components/Sample.tsx
import {
	getCpuMemoryHistory,
	getCpuUsage,
	getCpuUsageHistory,
	getGpuUsage,
	getGpuUsageHistory,
	getMemoryUsage,
} from "@/services/hardwareService";
import { useEffect, useState } from "react";

const Sample = () => {
	const [cpuUsage, setCpuUsage] = useState(0);
	const [memoryUsage, setMemoryUsage] = useState(0);
	const [gpuUsage, setGpuUsage] = useState(0);

	const [cpuHistory, setCpuHistory] = useState<number[]>([]);
	const [memoryHistory, setMemoryHistory] = useState<number[]>([]);
	const [gpuHistory, setGpuHistory] = useState<number[]>([]);

	useEffect(() => {
		const interval = setInterval(async () => {
			setCpuUsage(await getCpuUsage());
			setMemoryUsage(await getMemoryUsage());
			setCpuHistory(await getCpuUsageHistory(30));
			setMemoryHistory(await getCpuMemoryHistory(30));
			setGpuUsage(await getGpuUsage());
			setGpuHistory(await getGpuUsageHistory(30));
		}, 1000);

		return () => clearInterval(interval);
	}, []);

	return (
		<div>
			<p>CPU: {cpuUsage}%</p>
			<p>MEMORY: {memoryUsage}%</p>
			<p>GPU: {gpuUsage}%</p>

			<div>
				<h3>CPU History</h3>
				<p>Count: {cpuHistory.length}</p>
				<ul>
					{cpuHistory.map((item, index) => (
						<li key={index.toString()}>{item}</li>
					))}
				</ul>
				<h3>MEMORY History</h3>
				<p>Count: {memoryHistory.length}</p>
				<ul>
					{memoryHistory.map((item, index) => (
						<li key={index.toString()}>{item}</li>
					))}
				</ul>
				<h3>GPU History</h3>
				<p>Count: {gpuHistory.length}</p>
				<ul>
					{gpuHistory.map((item, index) => (
						<li key={index.toString()}>{item}</li>
					))}
				</ul>
			</div>
		</div>
	);
};

export default Sample;

// src/lib/components/sample.svelte
<script lang="ts">
import { onMount } from 'svelte';
import { getCpuMemoryHistory, getCpuUsage, getCpuUsageHistory, getGpuUsage, getGpuUsageHistory, getMemoryUsage } from '../../services/hardwareService';

const intervalSec = 1;

let cpuUsage = 0;
let memoryUsage = 0;
let gpuUsage= 0

let cpuHistory: number[] = [];
let memoryHistory: number[] = [];
let gpuHistory: number[] = [];

onMount(async () => {
  setInterval(async () => {
  cpuUsage = await getCpuUsage();
  memoryUsage = await getMemoryUsage();

  cpuHistory= await getCpuUsageHistory(30);
  memoryHistory = await getCpuMemoryHistory(30);

  gpuUsage = await getGpuUsage();
  gpuHistory = await getGpuUsageHistory(30);

}, intervalSec * 1000);
});



</script>

<div>
  <p>CPU: {cpuUsage}%</p>
  <p>MEMORY: {memoryUsage}%</p>
  <p>GPU: {gpuUsage}%</p>

  <div>
    <h3>CPU History</h3>
    <p>Count: {cpuHistory.length}</p>
    <ul>
      {#each cpuHistory as item}
        <li>{item}</li>
      {/each}
    </ul>
    <h3>MEMORY History</h3>
    <p>Count: {memoryHistory.length}</p>
    <ul>
      {#each memoryHistory as item}
        <li>{item}</li>
      {/each}
    </ul>
    <h3>GPU History</h3>
    <p>Count: {gpuHistory.length}</p>
    <ul>
      {#each gpuHistory as item}
        <li>{item}</li>
      {/each}
    </ul>
  </div>
</div>
